<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[random number: 6822906136]]>
    </line>
    <line>
      <![CDATA[this is query: select * from lt_logotp where mobile='6822906136']]>
    </line>
  </reporter-output>
  <suite started-at="2024-11-18T10:02:17 IST" name="Xpresso_Test" finished-at="2024-11-18T10:03:06 IST" duration-ms="48488">
    <groups>
      <group name="Sanity">
        <method signature="CalculatePremiumErrorMessageTest1.calculatePremiumError()[pri:1, instance:CareInsurance.Test.CalculatePremiumErrorMessageTest1@5b6ec132]" name="calculatePremiumError" class="CareInsurance.Test.CalculatePremiumErrorMessageTest1"/>
      </group> <!-- Sanity -->
    </groups>
    <test started-at="2024-11-18T10:02:17 IST" name="Sanity Test 1" finished-at="2024-11-18T10:03:06 IST" duration-ms="48488">
      <class name="CareInsurance.Test.CalculatePremiumErrorMessageTest1">
        <test-method is-config="true" signature="setup()[pri:0, instance:CareInsurance.Test.CalculatePremiumErrorMessageTest1@5b6ec132]" started-at="2024-11-18T10:02:17 IST" name="setup" finished-at="2024-11-18T10:02:25 IST" duration-ms="7845" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="calculatePremiumError()[pri:1, instance:CareInsurance.Test.CalculatePremiumErrorMessageTest1@5b6ec132]" started-at="2024-11-18T10:02:25 IST" name="calculatePremiumError" finished-at="2024-11-18T10:03:05 IST" duration-ms="40263" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "java.sql.Connection.createStatement()" because "this.connection" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "java.sql.Connection.createStatement()" because "this.connection" is null
at CareInsurance.Main.DbClass.executeQuery(DbClass.java:23)
at CareInsurance.Test.CalculatePremiumErrorMessageTest1.calculatePremiumError(CalculatePremiumErrorMessageTest1.java:98)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[random number: 6822906136]]>
            </line>
            <line>
              <![CDATA[this is query: select * from lt_logotp where mobile='6822906136']]>
            </line>
          </reporter-output>
        </test-method> <!-- calculatePremiumError -->
      </class> <!-- CareInsurance.Test.CalculatePremiumErrorMessageTest1 -->
    </test> <!-- Sanity Test 1 -->
  </suite> <!-- Xpresso_Test -->
</testng-results>
